### PR TITLE
changed readme.md for apis/userprofile

### PR DESCRIPTION
**Pull request by namujumd**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by josehui — APPROVED** [review]
lgtm

**Review by miguelarcilla — COMMENTED** [review]
I'm ok with this but will allow others to approve

**Comment by dprabhath** [comment]
Reviewed!

**Review by sanathu — APPROVED** [review]
lgtm

**Review by johanesalxd — APPROVED** [review]
all good

**Review by dprabhath — COMMENTED** [review]
Reviewed

**Pull request merged**
